name: Deploy Requin Web (Vite)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: 🚀 Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Obtener código
      uses: actions/checkout@v4

    - name: 📦 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: 📥 Instalar dependencias
      run: npm install

    - name: 🏗️ Construir proyecto
      run: npm run build

    - name: 🌐 Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: requinspa.com
        commit_message: '🚀 Automático: Deploy a GitHub Pages'

    - name: 📤 Subir a Servidor FTP
      continue-on-error: true
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /public_html/
